services:
  core:
    build: .
    environment:
      TELEGRAM_BOT_ID: "@diciobot"
      REDIS_HOST: "redis-12161.c270.us-east-1-3.ec2.cloud.redislabs.com"
      REDIS_PORT: "12161"
      REDIS_USER: "diciobot"
